### PR TITLE
Transition to async/await

### PR DESCRIPTION
**Pull request by homeyjd**
@arabold Thank you for creating such an easy-to-read and incredibly useful repo!

In this PR, I've completed:
- Transition to async/await (requires replacement of BlueBird, **DONE**)
- extend CloudFormation template with failure notification **(DONE)**
- add tests, I chose the Jest library for now **(DONE)**
- add AWS Console link URLs so message titles become clickable **(partially done)**
- _Future Goal_: ECS deploy messages

Also in this PR, fixes for issues:
- Add AutoScaling Parser https://github.com/arabold/aws-to-slack/issues/5
- Add threshold to CloudWatch chart https://github.com/arabold/aws-to-slack/issues/7
- Add KMS support for environment variables https://github.com/arabold/aws-to-slack/issues/8

AWS Lambda now [supports Node v8.10](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/).

In my other projects my team has really benefited from the easier reasoning/reading that comes with the async/await pattern. BlueBird is a solid and performant library and I think a perfect choice when you created this repo. I think for my purposes, the easier reasoning is worth a couple more hours to re-write the code into native async/await. I'm hoping with the Node-core team committing to the async/await keywords, that the pattern will live longer than any single library might.

I have added the first couple tests and deployed to my own environments successfully so far.  
*Looking for feedback!*

### CODE REVIEW

**Comment by arabold** [comment]
Sorry for the lack of feedback. Holidays were busier than anticipated 😆 This looks great though! I'm actually all for switching to `async`/`await` and this is great work. Especially as I'm currently not working with AWS anymore and thus have very little time to maintain the function myself. If you like I'm happy to grant you full access to the repo to simplify things.

I also like the reference to `widdix/aws-cf-templates` - never heard of this template repo before. Seems useful!

**Comment by arabold** [comment]
FYI I've just merged a couple of PRs that were sitting idle for way too long.

**Comment by homeyjd** [comment]
@arabold thank you for the feedback!

I’ve already included the CodeBuild integration PR, and will review the others. 

As I go, I’m also writing unit tests using example events. I’m in testing mode at the moment :). I plan to also update the event screenshots as adding threshold to graph and footer links for event source changes the look slightly. 

If you’re open to granting access to the repo, I’d be happy to resolve conflicts and get this merged. I’m about a week away from finishing testing.

**Comment by arabold** [comment]
Yeah, the PR is large and I only glanced through it yet. I'm polishing up the current `master` (without your changes in this PR) and will release a new version 1.1.8 in the next few minutes.

**Comment by homeyjd** [comment]
Taking a break on this.  

I've deployed to my own environments.  Will take a week to wait and see if any problems are apparent.

**Comment by homeyjd** [comment]
Hey @arabold Seeing as more PR's keep rolling in, I'm going to merge.  Getting harder for me to keep up with all the branch-translation.

I think we're landing in a pretty good place, but I haven't officially seen the last 3 days of changes working in production.  Going to release to my own stacks today (I modified Makefile to add a `lambda-update` routine).  I'd suggest maybe holding off on releasing a rev-bump until we see a couple successful messages come through Slack.

I've been dev'ing off master on my fork so I could work faster. If I find anything I need to update, would you mind if I pushed to master-upstream?

**Pull request merged**
