### PR TITLE
Added support for AWS inspector notifications

### PR DESCRIPTION
**Pull request by HyperBrain**
I added support for [AWS Inspector](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_introduction.html) notifications.
Inspector runs can be configured to send notifications through SNS, as they are normally configured to last some hours.

### CODE REVIEW

**Comment by HyperBrain** [comment]
Will add some improvements. Then it can be reviewed.

**Comment by HyperBrain** [comment]
@arabold Tis is ready for review now!

**Comment by arabold** [comment]
Thanks for the contribution. I've found this list of rules with well-known ARNs: https://docs.aws.amazon.com/inspector/latest/userguide/inspector_rules-arns.html. This would further help making the alerts more user friendly.

**Comment by HyperBrain** [comment]
Did you intend to link the list you found? 😄

**Comment by arabold** [comment]
I've added a linkt to https://docs.aws.amazon.com/inspector/latest/userguide/inspector_rules-arns.html in the original comment 🤣

**Comment by HyperBrain** [comment]
Great document! I will add a rules package name map, so the package name will be shown instead of the unreadable arns.

**Comment by HyperBrain** [comment]
Done!

**Pull request merged**
