### PR TITLE
Use CloudFormation condition to deploy either local or public package

### PR DESCRIPTION
**Pull request by nason**
I've been using this lambda a lot over the part few weeks to set up all kinds of alerts. Its great! Thank you!

I've wanted to deploy local changes to it a few times, and this is how I've been making that happen. I don't know if you're interested in merging this upstream, but I thought I'd share either way!

- If you deploy this stack with no `DirectDeploy` parameter, everything works the same.
- If you deploy this stack with a `DirectDeploy` parameter, it will deploy the package from your local `build/release.zip`

### CODE REVIEW

**Comment by homeyjd** [comment]
I like the idea conceptually, but I've never seen that syntax.  It's missing from the docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html
I would imagine it would only work when launching from the `aws-cli`?

The `readme.md` contains a direct link to launch a CF stack, which of course wouldn't work with a local path.  Having a "DirectDeploy" parameter might be confusing for a CF-newcomer.  

For now, I've been using the [`Makefile`'s `lambda-update`](https://github.com/arabold/aws-to-slack/blob/master/Makefile#L11) to build-and-deploy changes. CloudFormation is great for configuration, permissions, and resource setup, but it's slow and cumbersome when just doing code deploys. 

I might lean towards keeping the CF template clear of local paths.  Thoughts?

**Comment by nason** [comment]
Totally understandable @homeyjd! 

My use case is: We have a bunch of custom notifiers today, spread across different channels, and I'd like to start moving towards using this notifier in more places, as well as contributing back to this project.

In my fork I went a step further than I did here and [added a `make deploy` and the concept of deploy targets](https://github.com/narratorai/aws-to-slack/commit/9b6ca20abe24dce31c3cf4000a9b1c4ec0562bf0) so I can have multiple handlers deployed for different channels, with either the public stack or a custom one.

> I like the idea conceptually, but I've never seen that syntax. It's missing from the docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html
I would imagine it would only work when launching from the aws-cli?

Yes! Sorry that wasn't clear. This is intended to be used with [`cloudformation package`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html)

> I might lean towards keeping the CF template clear of local paths. Thoughts?

I think this is a good decision. I wanted to share just in case you or anyone else was running into issues managing multiple deployments and testing code like I was. Its helpful to me so it can live in my fork 😎

**Comment by homeyjd** [comment]
@nason Thanks for the heads-up on `aws cf package` -- haven't used that one yet. Really liked the idea of having a release process within the repo, I think it was just the S3 requirement and `package`'s pre-processing that had me hung up.

What would you think of this for the base repo: https://github.com/arabold/aws-to-slack/pull/41
It auto-runs `make package` when needed, allowing the release.zip file to be removed without breaking any deployment commands.
Uses .env files instead of JSON, so easier to read for any bash-based automation tool without requiring `jq`.
Auto-pushes latest code after performing the `deploy`, so no need for S3 to be an intermediary.

Thoughts?

**Comment by nason** [comment]
Thank you! That looks great to me, and can definitely support my needs.

I don't know a ton about publishing public stacks so I can't comment on that front (would love to learn more!)

**Pull request closed without merging**
