### PR TITLE
Update codedeploy parser to handle sns

### PR DESCRIPTION
**Pull request by greyvugrin**
While attempting to trigger codedploy events yesterday I couldn't find a way to trigger them in a format that the current parser expects, only via sns (adding trigger within deployment group only has the option for sns).

This updates the codedeploy parser created by #21 to expect an sns message instead (like the cloudwatch one).

If the existing parser is still needed, let me know and I can move this into a new file so that we can still fall back on the current behavior.

EDITED: Test event:

```
{
  "Records": [
    {
      "EventSource": "aws:sns",
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:us-west-2:111111111:my-app:some-hash",
      "Sns": {
        "Type": "Notification",
        "MessageId": "unique-message-hash",
        "TopicArn": "arn:aws:sns:us-west-2:111111111:my-app",
        "Subject": "CREATED: AWS CodeDeploy d-DEPID in us-west-2 to MyApplication",
        "Message": "{\"region\":\"us-west-2\",\"accountId\":\"111111111\",\"eventTriggerName\":\"Deployment Status Updates - engagement\",\"applicationName\":\"MyApplication\",\"deploymentId\":\"d-DEPID\",\"deploymentGroupName\":\"staging\",\"createTime\":\"Thu Dec 13 20:23:06 UTC 2018\",\"completeTime\":null,\"status\":\"SUCCEEDED\"}",
        "Timestamp": "2018-12-13T20:23:07.179Z",
        "SignatureVersion": "1",
        "Signature": "xxxxxxxxxx",
        "SigningCertUrl": "https://xxxxxxxxx",
        "UnsubscribeUrl": "https://xxxxxxxxx",
        "MessageAttributes": {}
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by thesuavehog** [comment]
I used the SNS format for the CodePipeline parser I made in PR #28 
That seems like the way to trigger these types of events and provides all the info needed.

**Comment by greyvugrin** [comment]
@thesuavehog sweet - good to know this is the right approach.

**Comment by greyvugrin** [comment]
@bkono let me know what you think

**Comment by bkono** [comment]
@greyvugrin Interesting approach. I actually go directly from both CodeBuild and CodeDeploy CloudWatch events to invoking the lambda, no SNS or CodePipeline involved in many cases, so this change would break the existing codebase of several clients. In particular, for existing setups without a pipeline (or no desire to use one, if CodeDeploy is manually or programmatically triggered), its convenient to just hook to the events generically and catch everything. Seems like a worthwhile change to have an alternative SNS based parser, but I'm not sure making it mandatory is the right choice.

In case there's any interest, here's a clip of some ugly CFN I use for connecting the events:
```
CodeDeployNotificationRule:
      Type: AWS::Events::Rule
      Properties:
        Description: "CodeDeployNotificationRule"
        State: "ENABLED"
        Targets:
          - Arn: !ImportValue SlackFunctionArn
            Id: !Sub "${Env}CodeDeployNotificationLambdaTarget"
        EventPattern:
          source: 
            - "aws.codedeploy"
          detail-type: 
            - "CodeDeploy Deployment State-change Notification"
          detail:
            state: 
              - FAILURE
              - START
              - STOP
              - QUEUED
              - READY
              - SUCCESS
            application: 
              - !Ref Env
  PermissionForCodeDeployNotificationRuleToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !ImportValue SlackFunctionArn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt CodeDeployNotificationRule.Arn
```

**Comment by thesuavehog** [comment]
Are the data structures in the direct event from CodeDeploy vs the SNS "Message" JSON similar?
I.e. could the parser detect the encapsulation in the SNS structure and then parse either format? The desired output is the same - it's just the structure of the event right?

One reason I think the SNS structure is very valuable - for all events - is that for new users on AWS, virtually every service allows you to fire events at an SNS Topic so once you set one up it's simple to get everything firing to Slack that way. The downside is you lose the filtering in CloudWatch on which events to send but I have found it REALLY handy to get things going with SNS and then come back later and filter if the volume is too high from a service.

**Comment by greyvugrin** [comment]
@bkono right on, thanks for the extra info. I'll update this to have a new name (codedeploySns.js), and add it as an additional option

**Comment by bkono** [comment]
@greyvugrin Glancing at your PR, it seems like the values are almost the same (except deploy status vs state), but the nested structure and key names are different. Personally I'd like to see both options available in a user-friendly way. I haven't been keeping up on what the pattern is in this particular repo, but I'd usually suggest 1 of 2 things. Either: 1) burying the type of event being parsed in the single CodeDeployParser by splitting the current parser and your parser off to two separate funcs, ala parseSNS(message) and parseCloudWatch(event), and then return back the same output, and make the decision on which to call based on evaluating the inbound obj. 2) Name yours as a CodeDeploySNSParser and dual-name the existing one as CodeDeployCloudWatchParser with a comment so we can consider the other name deprecated.

@thesuavehog Agreed that SNS is valuable as well. I find I use it in the wild for different use cases than the CloudWatch scenario. Just as an example, SNS would have required altering the deployment groups for a client, which was something we intentionally were avoiding for various non-technical reasons. CloudWatch allows a way to attach outside of that, with no changes to the existing setup. And as a little background, which probably isn't relevant now, going back a year or two (or more?) most of the blog posts and guides were around using CloudWatch events. I'd expect thats shifted to SNS by now, as it provides a lot of additional capabilities.

**Comment by thesuavehog** [comment]
Yeah - I'm not saying whether SNS vs CloudWatch is better, more that the intro/beginner info online tends to aim towards "fire stuff at SNS and then subscribe", while the more intermediate/advanced info tends to be more "use CloudWatch to do fancy handling". I've used both (different use cases) and one thing I found great about this Lambda function was how easy it was (as a beginner) to "set it and forget it" and fire events at it. Which, granted, is starting to clog up my Slack channel so I will need to do CloudWatch filtering soon - but it is great for people getting going.

I agree w your proposed approach of separating the event parsing from the output formatting so that either can work.

**Comment by lorengordon** [comment]
I believe this project tries all the parsers, and uses the parser that resolves the promise successfully. At least, that's how it seemed to work when I submitted [CodeCommit parsers](https://github.com/arabold/aws-to-slack/pull/24).

So, probably go with whichever way makes it easiest to re-use as much code as possible, but it certainly should work to keep both parsers in separate files without stepping on each other. :)

**Comment by thesuavehog** [comment]
Good point. I forgot it's not a "registration" model but a "try all parsers until one says it handled it" so both should co-exist fine.

**Comment by greyvugrin** [comment]
@bkono went with approach 2. Let me know if you have any more input, otherwise would mind reviewing? Can't request reviews unfortunately

**Review by bkono — APPROVED** [review]
Looks great to me.

**Comment by bkono** [comment]
@greyvugrin based on @lorengordon 's comment about them coexisting (I didn't remember if it was a registration model or not for the consumer), this looks great. Thanks for doing it, and checking in to make sure you didn't break anyone. ;)

**Comment by greyvugrin** [comment]
@bkono absolutely. Thanks all for chiming in

**Comment by greyvugrin** [comment]
@arabold hey there - would you have a second to review this?

**Comment by arabold** [comment]
Amazing! Thanks for the valuable discussion in this thread and I'm truly sorry not getting back to you sooner. I'll merge this right away and prepare a new release. Thanks again.

**Comment by greyvugrin** [comment]
@arabold you got it! No worries, life gets busy. Cheers

**Pull request merged**
