### PR TITLE
getting the commit message when necessary for repository commits

### PR DESCRIPTION
**Pull request by elChapoSing**
Closing The issue https://github.com/arabold/aws-to-slack/issues/51

When I try to run it on the actual lambda server I get 

> TypeError: parser.parse(...).then is not a function
    at BbPromise.any._.map.Parser (/var/task/src/index.js:34:4)

and I have absolutely no idea why. My promise handling should be ok. Is there something specific to Lambda AWS as far as promises are concerned ?

Happy for someone to have a look and opine.

Once this one works I'll do the same for the `pullrequests` parser.

### CODE REVIEW

**Comment by lorengordon** [comment]
Rather than relying on `refType === branch`, perhaps just get the `commitId` from the event detail. If present, use that to get the commit message. If absent, skip.

* https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#codecommit_event_type

```
{
      "version": "0",
      "id": "01234567-0123-0123-0123-012345678901",
      "detail-type": "CodeCommit Repository State Change",
      "source": "aws.codecommit",
      "account": "123456789012",
      "time": "2017-06-12T10:23:43Z",
      "region": "us-east-1",
      "resources": [
        "arn:aws:codecommit:us-east-1:123456789012:myRepo"
      ],
      "detail": {
        "event": "referenceCreated",
        "repositoryName": "myRepo",
        "repositoryId": "12345678-1234-5678-abcd-12345678abcd",
        "referenceType": "tag",
        "referenceName": "myTag",
        "referenceFullName": "refs/tags/myTag",
        "commitId": "3e5983EXAMPLE"
      }
 }
```

**Comment by homeyjd** [comment]
Thank you for the PR @elChapoSing!  (and thank you @lorengordon for the sample event!) I've pushed a new commit to your branch that uses the async/await pattern and fixes ESLint issues.  Let me know what you think.

It'd be great to include a test case in the tests/parsers/ folder that contains a full example of the event pattern this parser will match!

Regarding the BdPromise error... Unfortunately, only arabold has access to the S3 buckets to update the CloudFormation-referenced zip files.  So everytime a new CloudFormation stack is released, it's deploying code based on an older version.

I recommend re-deploying the code from your local `aws-to-slack` folder to fix this.
```
AWS_REGION=your-region LAMBDA_NAME=your-lambda make deploy
```

Also, one day soon we may merge an additional upgrade from my fork.  I put a [warning in the Readme](https://github.com/homeyjd/aws-to-slack#try) to hopefully avoid these problems.  The fork simplifies parsers even more by separating event-matching from response-generation.

**Comment by lorengordon** [comment]
That update looks great @homeyjd! I was worried about the lambda not having permissions to make the new API calls, and the failure getting swallowed, so happy to see them logged!

**Comment by elChapoSing** [comment]
@homeyjd thank you sir ! Fits the style of the app much better than my own piece of code. Now on to @arabold to allow merging. Will add the `pullrequests` parser following @homeyjd example style as well.

**Comment by homeyjd** [comment]
Happy to merge :). 
If you get a chance to add tests for `codecommit` and `pullrequests` in your PR that'd be awesome!
Thanks, @elChapoSing!

**Comment by elChapoSing** [comment]
am unfortunately not sure how to add tests. In which file can I see how the other tests were constructed ?

**Comment by elChapoSing** [comment]
ok it's in the `test` folder. duh.

**Pull request merged**
